apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-cnfde6-site-testpmd-pod
  namespace: cnfde6-site-subscription
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: v1
        kind: Pod          
        metadata:           
          name: bunny-ears-workload-2core
          namespace: cnfde6
          annotations:                       
            k8s.v1.cni.cncf.io/networks: nic1port1, nic1port2, nic2port1, nic2port2
            cpu-load-balancing.crio.io: "true"
        spec:         
          runtimeClassName: performance-performance
          restartPolicy: Never      
          containers:  
          - name: nic1
            image: quay.io/krister/centos8_nfv-container-dpdk-testpmd:latest
            imagePullPolicy: Always 
            env:         
            - name: PROMISC_DEVICES    
              value: "n"    
            - name: DISABLE_CPU_LOAD_BALANCE
              value: "n"                          
            - name: PEER_A_MAC
              value: "3c:fd:fe:a9:cf:34"
            - name: PEER_B_MAC
              value: "3c:fd:fe:ee:4c:d0"
            - name: SRIOV_ID_A
              value: "NIC1PORT1"                                   
            - name: SRIOV_ID_B
              value: "NIC1PORT2"
            - name: MTU
              value: "9000"
            securityContext:
              capabilities:
                add: ["IPC_LOCK","SYS_ADMIN"]
            resources:
              limits:
                cpu: 3
                memory: "1000Mi"
                hugepages-1Gi: "2Gi"
              requests:
                cpu: 3
                memory: "1000Mi"
                hugepages-1Gi: "2Gi"
            volumeMounts:
            - mountPath: /dev/hugepages
              name: hugepage
          - name: nic2
            image: quay.io/krister/centos8_nfv-container-dpdk-testpmd:latest
            imagePullPolicy: Always
            env:
            - name: PROMISC_DEVICES
              value: "n"
            - name: DISABLE_CPU_LOAD_BALANCE
              value: "n"
            - name: PEER_A_MAC
              value: "3c:fd:fe:a9:cf:34"
            - name: PEER_B_MAC
              value: "3c:fd:fe:ee:4c:d0"
            - name: SRIOV_ID_A
              value: "NIC2PORT1"
            - name: SRIOV_ID_B
              value: "NIC2PORT2"
            - name: MTU
              value: "9000"
            securityContext:
              capabilities:
                add: ["IPC_LOCK","SYS_ADMIN"]
            resources:
              limits:
                cpu: 3
                memory: "1000Mi"
                hugepages-1Gi: "2Gi"
              requests:
                cpu: 3
                memory: "1000Mi"
                hugepages-1Gi: "2Gi"
            volumeMounts:
            - mountPath: /dev/hugepages
              name: hugepage
          volumes:
          - name: hugepage
            emptyDir:
              medium: HugePages
